# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'MepuzzExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Mepuzz', '~> 1.0'
  # Pods for MepuzzExample

  target 'MepuzzExampleUITests' do
    # Pods for testing
  end

end
